### ISSUE TITLE
DynamoDB Global Stream Name

### ISSUE THREAD

**Issue by johncolmdoyle** [mhlabs/cfn-diagram#24] opened 2021-02-01 16:21 UTC
When a DynamoDB Global Table is created, a stream is generated and named by the system. The name involves a timestamp, with a precision down to the milliseconds. This appears to cause `cfn-dia` to think the value is referring to a dependency.

Example stream:
```
arn:aws:dynamodb:REGION:AWS-ACCOUNT:table/TABLE-NAME/stream/2021-01-16T19:47:47.531
```

## Expected Behavior
Be able to reference a DynamoDB Stream with a timestamp name within an IAM policy, and be able to set the stream as an Event Source for a Lambda.

## Current Behavior
An exception is generated: 
```
TypeError: Cannot read property 'Resources' of undefined
    at dependency.value.dependency.value.filter (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:195:50)
    at Array.filter (<anonymous>)
    at getDependencies (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:190:41)
    at makeGraph (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:79:28)
    at renderTemplate (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:237:26)
    at Object.generate (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/graph/MxGenerator.js:268:17)
    at Command.program.command.alias.option.option.option.option.description.action (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/commands/draw.io/index.js:27:23)
    at Command.listener [as _actionHandler] (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/johndoyle/.nvm/versions/node/v10.15.1/lib/node_modules/@mhlabs/cfn-diagram/node_modules/commander/index.js:865:18)
```

The HTML option does render several elements from the template, but it is incomplete.  

## Detailed Description

Due to the presence of the period in the name, several code snippets presume its part of a dependency:

MxGenerator.js:195
```
for (const dependency of dependencies) {
    dependency.value = dependency.value.filter((p) => {
      const split = p.split(".");
      if (split.length === 2) {
        return templateCache.templates[split[0]].Resources[split[1]];
      }
      return template.Resources[p];
    });
  }
```

Vis.js:155
```
  for (const dependency of dependencies) {
    dependency.value = dependency.value.filter((p) => {
      const split = p.split(".");
      if (split.length === 2) {
        return templateCache.templates[split[0]].Resources[split[1]];
      }
      return template.Resources[p];
    });
  }
```

## Possible Implementation

Added a check to see if there was a property called Resources, and this got me past the error. 
```
      if (split.length === 2) {
        if (templateCache.templates[split[0]] && templateCache.templates[split[0]].hasOwnProperty('Resources')) {
          return templateCache.templates[split[0]].Resources[split[1]];
        }
      }
```

Not sure how it is getting into the dependencies list, to begin with, but suspect it might be the IAM policy listing it as a Resource?

```
    "CFN-Name": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "dynamodb:DescribeStream",
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:dynamodb:REGION:AWS-ACCOUNT:table/TABLE-NAME/stream/2021-01-16T19:47:47.531"
            },
```

**Comment by ljacobsson** [comment] 2021-02-04 19:04
Hi @johncolmdoyle. Thanks for reporting!

Trying to reproduce this. Would it be possible to share some CDK code that causes this?

Thanks!

**Comment by johncolmdoyle** [comment] 2021-02-04 19:09
Yep, sure thing - the code I was trying to diagram is here: 

https://github.com/johncolmdoyle/postman-hackathon/blob/main/lib/cdk-postman-stack.ts

**Comment by ljacobsson** [comment] 2021-02-04 20:00
Thanks!

Think it'd be difficult to test on it since I don't have access to any deployed global tables

However, now that I reread your bug report it's obvious that it's the timestamp that did I. Added check that the first part of the split actually exists as a nested template

**Comment by ljacobsson** [comment] 2021-02-04 20:06
Have just released the fix for this. Will close the issue.

Please reopen if it persists :+1:

**Closed by ljacobsson** 2021-02-04 20:06 UTC
Labels: bug
